### ISSUE TITLE
求教：如何在当前原生开发中优雅的集成flutter

### ISSUE THREAD

**Issue by CatTalk2** [yang7229693/flutter-study#1]
非常感谢博主无私的分享；

目前还没看到比较成熟的原生集成flutter的方案，可能对很多新手来说，这也是开始尝试flutter遇到的第一个难题，博主能否推荐相关文章或示例，感激之至☺️

**Comment by longshao521** [comment]
https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps#experiment-integrate-flutterviewcontroller

**Comment by yang7229693** [comment]
https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps

这篇文章有如何集成，也可以参照我的文章，写的很粗略，但是关键步骤都有

**Comment by roche1990** [comment]
请问有没有碰到在现有的iOS项目中集成后，flutter_webview_plugin 无法使用
