### ISSUE TITLE
关于相机定制的疑问想请教您一下

### ISSUE THREAD

**Issue by WhyNoter** [yang7229693/flutter-study#2]
请教一下，您在相机定制那块，ui部分是全部都是用原生写的，还是部分用flutter覆盖在原生ui上呢

**Comment by yang7229693** [comment]
原生的flutter实现，拍照预览是用的camera插件，相当于一个FlutterView，在上面添加原生控件很方便，但是camera插件会有问题的，我文章里面说了的哈，camera api以及crash，最好自己重新写一下camera插件的Android端。
