### ISSUE TITLE
文中错别字

### ISSUE THREAD

**Issue by wumingXL** [yang7229693/flutter-study#5]
markNeedsBuild内部，则是通过标记element为diry。应该是dirty。
flutter中的变量名字为_dirty

  /// Returns true if the element has been marked as needing rebuilding.
  bool get dirty => _dirty;
  bool _dirty = true;

**Comment by wumingXL** [comment]
Flutter布局详解文章中

**Comment by yang7229693** [comment]
多谢反馈
